[site]
title = "Bing Fan"
description = "PhD Candidate at the Purdue University."
favicon = "/favicon.svg"
last_updated = "Feb 21, 2026"

[author]
name = "Bing Fan"
title = "PhD Candidate of Economics"
institution = "Purdue University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "fan399@purdue.edu"
location = "Lafayette, IN, United States"
location_url = "https://maps.google.com"
location_details = [
  "KRAN 320, Business School,",
  "Purdue University, West Lafayette, IN"
]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org"
github = "https://github.com"
linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Blogs"
type = "page"
target = "blogs"
href = "/blogs"

# [[navigation]]
# title = "Awards"
# type = "page"
# target = "awards"
# href = "/awards"

[[navigation]]
title = "Misc"
type = "page"
target = "miscellaneous"
href = "/miscellaneous"

#[[navigation]]
#title = "Services"
#type = "page"
#target = "services"
#href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
